### ISSUE TITLE
Performance are lower than ortools solver

### ISSUE THREAD

**Issue by MehdiZouitine** [zcaicaros/DRL-MTSP#1]
Thank you for the implementation. After several days spent on this code I still can't show that the implementation exceeds the results of ortools. Is this normal?

**Comment by zcaicaros** [comment]
This seems abnormal.

How did u implement using ortools?

**Comment by MehdiZouitine** [comment]
For each problem instance, I compare the longest tour given by GNN and by ORtools. For example if we consider 5 vehicles 50 cities and a scale of 10000, the maximum tour length for ORtools is about 2.12 on average. However the results of the paper seem to show that ORtools only achieves 2.356 reward (which is much worse than the actual result of ortools).
Furthermore the implementation with GNN does not manage to exceed 2.12 of reward

Thanks a lot for your help!

**Comment by zcaicaros** [comment]
I've checked the paper.  Do note that 2.356 is the performance of OrTools with a total of 1 second of solving time. So what is your time limit for Ortools? And what is the performance of GNN? Is it close to 2.115 (as reported in the paper)?

Please also note that this repo is a "reimplement" of the paper, where we made some changes (refer to our `README.md`). The instances are also different from those tested in the original paper, which may incur some differences in the performance (we have asked the author of the original paper, however, they refused to share their testing data).

**Comment by zcaicaros** [comment]
Please also note that this repo is a "reimplement" of the paper, where we made some changes (refer to our `README.md`). The instances are also different from those tested in the original paper, which may incur some differences of the performance (we have asked the author of the original paper, however they refused to share their tested data).

**Comment by zcaicaros** [comment]
If there are still concerns, can re-open this issue.

**Comment by MehdiZouitine** [comment]
Hello, thank you for your answers. After having experimented more deeply : GNN does not perform better than ortools for the instance with 5 agents and 50 cities -> Ortools (1800s) gets 2.15 and GNN 2.3. 

It is claimed that the implementation provides better results than the paper, how are you sure?

**Comment by zcaicaros** [comment]
Hi, thanks for the reply. Based on your results, it seems GNN is inferior to OrTools on the 50-5 problem size. How about the other size? Since the author of the original paper has provided their code (link given in my `README.md`). Maybe you can train their model and test it on my dataset. If I recall correctly, their performance is generally worse than our implementation (but very close).
